language: go

go:
  - master

os:
  - linux

dist: trusty
sudo: required

env:
  - DEP_VERSION="0.4.1"


before_install:
  - sudo apt-get -qq update
  #installing dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  #installing dependencies
  - dep ensure

  #build binary
  - go build cmd/gosint.go
